version: '3.5'
services:
    UniSystem_Postgres:
        image: postgres:latest
        container_name: UniSystem
        ports:
            - "5434:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: asunder32
            POSTGRES_DB: UniSystem 1.0
        volumes:
          - ./databases/postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "erikviana32@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "asunder32"
        ports:
            - 5050:80
        depends_on:
            - UniSystem_Postgres
